### PR TITLE
return error messages on validation error

### LINKED ISSUE #20: Return meaningful error message on Validation failure
Current behaviour is that we just return BAD_REQUEST... However, this is not enough because then we don't know which field(s) failed validation.

Current code:
 https://github.com/rambler-digital-solutions/actix-web-validator/blob/master/src/error.rs#L51-L55 

If we change this method we can return a list of errors, or at least the first one

### PR DESCRIPTION
**Pull request by c650**
Fixes #20

### CODE REVIEW

File: src/error.rs [hunk 1]
```diff
@@ -50,6 +50,16 @@ impl From<validator::ValidationErrors> for Error {
 
 impl ResponseError for Error {
     fn error_response(&self) -> HttpResponse {
-        HttpResponse::new(StatusCode::BAD_REQUEST)
+        HttpResponse::build(StatusCode::BAD_REQUEST).body(match self {
+            Self::Validate(e) => format!(
+                "{{\"message\": \"invalid {}\" }}",
```
Comment (singulared) [inline src/error.rs:55]: Maybe better to use plain text for error reporting by default like actix-web?

**Review by singulared — CHANGES_REQUESTED** [review]

File: src/error.rs (hunk 1 above)
Comment (c650) [reply src/error.rs:55]: so just the errors joined with , is fine?

Comment (singulared) [reply src/error.rs:55]: I think yes)
